---
# Create the Elasticsearch security group
- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - ec2

# Create a single master Elasticsearch instance
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a master Elasticsearch instance
      ec2:
         key_name: fender-dev
         instance_type: t2.small
         region: us-west-2
         image: ami-9abea4fb
         group: elasticsearch
         wait: true
         exact_count: 1
         count_tag:
            estype: master
         instance_tags:
            Name: elasticsearch
            estype: master
      register: ec2
      tags:
        - ec2-launch

    - name: Add instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Add instance public IPs to master group
      add_host: hostname={{ item.public_ip }} groups=elasticsearch_master
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
      with_items: ec2.instances
      tags:
        - ec2-launch

# Create two slave Elasticsearch instances
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision two slave Elasticsearch instances
      ec2:
         key_name: fender-dev
         instance_type: t2.small
         region: us-west-2
         image: ami-9abea4fb
         group: elasticsearch
         wait: true
         exact_count: 2
         count_tag:
            estype: slave
         instance_tags:
            Name: elasticsearch
            estype: slave
      register: ec2
      tags:
        - ec2-launch

    - name: Add instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Add instance public IPs to slave group
      add_host: hostname={{ item.public_ip }} groups=elasticsearch_slave
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=10 timeout=320 state=started
      with_items: ec2.instances
      tags:
        - ec2-launch

- hosts: ec2hosts
  name: Install Java JDK 1.8.0_91
  user: ubuntu
  gather_facts: true
  roles:
    - java

- hosts: ec2hosts
  name: Install Elasticsearch on all machines
  user: ubuntu
  gather_facts: true
  roles:
    - elasticsearch-tw

- hosts: elasticsearch_master
  name: Configure Elasticsearch on the master server node
  user: ubuntu
  gather_facts: true
  roles:
    - elasticsearch-master 

- hosts: elasticsearch_slave
  name: Configure Elasticsearch on the slave server nodes
  user: ubuntu
  gather_facts: true
  roles:
    - elasticsearch-slave
