---
# Create a single master Elasticsearch instance
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a master Elasticsearch instance
      ec2:
         key_name: knife_access
         instance_type: t2.micro
         region: us-west-2
         image: ami-9abea4fb
         group_id: sg-e6e72183
         wait: true
         exact_count: 1
         count_tag:
            estype: master
         instance_tags:
            Name: elasticsearch
            estype: master
      register: ec2
      tags:
        - ec2-launch

    - name: Add instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Add instance public IPs to master group
      add_host: hostname={{ item.public_ip }} groups=elasticsearch_master
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=20 timeout=320 state=started
      with_items: ec2.instances
      tags:
        - ec2-launch

# Create two slave Elasticsearch instances
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision two slave Elasticsearch instances
      ec2:
         key_name: knife_access
         instance_type: t2.micro
         region: us-west-2
         image: ami-9abea4fb
         group_id: sg-e6e72183
         wait: true
         exact_count: 2
         count_tag:
            estype: slave
         instance_tags:
            Name: elasticsearch
            estype: slave
      register: ec2
      tags:
        - ec2-launch

    - name: Add instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Add instance public IPs to slave group
      add_host: hostname={{ item.public_ip }} groups=elasticsearch_slave
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=20 timeout=320 state=started
      with_items: ec2.instances
      tags:
        - ec2-launch

- hosts: ec2hosts
  name: Install Java JDK 1.8.0_91
  user: ubuntu
  gather_facts: true
  roles:
    - java

- hosts: elasticsearch_master
  name: Install and configure Elasticsearch on the master server node
  user: ubuntu
  gather_facts: true
  roles:
    - { role: elasticsearch, es_instance_name: elasticsearch-1, es_heap_size: "1g",
    es_config: {
        cluster.name: "fender-test",
        "discovery.zen.ping.multicast.enabled": false,
        discovery.zen.ping.unicast.hosts: "elasticsearch-1, elasticsearch-2, elasticsearch-3",
        node.data: false,
        node.master: true,
        bootstrap.mlockall: false,
        discovery.zen.ping.multicast.enabled: false }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible
    es_plugins:
      - plugin: elasticsearch/license
        version: latest
  with_items: ec2.instances
