---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a master Elasticsearch instance
      ec2:
         key_name: knife_access
         instance_type: t2.micro
         region: us-west-2
         image: ami-9abea4fb
         group_id: sg-e6e72183
         wait: true
         count: 1
         count_tag:
            Name: elasticsearch-master
         instance_tags:
            Name: elasticsearch
            estype: master
      register: ec2
      tags:
        - ec2-launch

    - name: Add instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Add instance public IPs to master group
      add_host: hostname={{ item.public_ip }} groups=elasticsearch_master
      with_items: ec2.instances
      tags:
        - ec2-launch

    - name: Wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=20 timeout=320 state=started
      with_items: ec2.instances
      tags:
        - ec2-launch

- hosts: ec2hosts
  name: Install Java JDK 1.8.0_91
  user: ubuntu
  gather_facts: true
  roles:
    - java

- hosts: ec2hosts
  name: Install Elasticsearch
  user: ubuntu
  gather_facts: true
  roles:
    - elasticsearch
