---
- name: Download Elasticsearch onto target machines
  get_url: url="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb" dest="/tmp/elasticsearch-2.3.3.deb" validate_certs=no
  tags:
    - elasticsearch
    - download

- name: Install newly-downloaded .deb distribution of Elasticsearch
  command: "dpkg -i /tmp/elasticsearch-2.3.3.deb"
  sudo: yes
  tags:
    - elasticsearch
    - install
