---
- name: Download Java from Oracle
  command: "wget -q -O /tmp/jdk-8u91-linux-x64.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-linux-x64.tar.gz creates=/tmp/jdk-8u91-linux-x64.tar.gz"
  tags:
    - java

- name: Extract to /usr/bin/jdk1.8.0_91
  unarchive: src=/tmp/jdk-8u91-linux-x64.tar.gz dest=/usr/bin copy=no
  sudo: yes
  tags:
    - java