---
- name: Apply template for slave node to system
  template: src=elasticsearch.yml.slave.j2 dest=/etc/elasticsearch/elasticsearch.yml
  sudo: yes

- name: Start the Elasticsearch service
  service: name=elasticsearch state=started
  sudo: yes
