---
#- name: Create EC2 VPC for use
#  ec2_vpc:
#    state: present
#    region: "{{ region }}"
#    cidr_block: "{{ master_cidr_block }}"
#    resource_tags: { "Environment" : "Development", "Name" : "fender" }
#    internet_gateway: "{{ internet_gateway }}"
#    subnets:
#      - cidr: "{{ subnet_cidr_block }}"
#      - az: "{{ a_zone }}"
#      - resource_tags: { "Tier" : "Elasticsearch" }
#    route_tables:
#      - subnets:
#        - "{{ subnet_cidr_block }}"
#        routes:
#          - dest: 0.0.0.0/0
#            gw: igw
#    wait: yes
#  register: vpc

- name: Create Elasticsearch EC2 security group
  ec2_group:
    name: elasticsearch
    description: A security group for Elasticsearch servers
#    vpc_id: "{{ item.id }}"
    region: us-west-2
    state: present
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9200
        to_port: 9200
        group_name: elasticsearch
      - proto: tcp
        from_port: 9300
        to_port: 9300
        group_name: elasticsearch
#  with_items: vpc.subnets
