---
- name: Create Elasticsearch EC2 security group
  ec2_group:
    name: elasticsearch
    description: A security group for Elasticsearch servers
    vpc_id: vpc-6c41a209
    region: us-west-2
    state: present
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9200
        to_port: 9200
        group_name: elasticsearch
      - proto: tcp
        from_port: 9300
        to_port: 9300
        group_name: elasticsearch
